### ISSUE TITLE
Use NN token splitter

### ISSUE THREAD

**Issue by m09** [src-d/tm-experiments#27]
Currently we use a split on underscores to split subtokens from words. We have a [NN tokenizer](https://github.com/src-d/ml-core/blob/master/sourced/ml/core/algorithms/token_parser.py) that we could use instead to reduce noise.

Since the NN tokenizer is really slow on CPU, it should be possible to enable it only if a GPU is available.

**Comment by r0mainK** [comment]
Okay, as discussed this morning in a call with @m09 we will add this as an optionnal feature, as w/o GPU the NN tokenizer is painfully slow. I will push tomorrow the changes.
